
var wordCorpus =
	[{ "eng": "mister, miss, madam", "jap": "さん" },
	{ "eng": "this one (polite for this person)", "jap": "こちら" },
	{ "eng": "(topic particle)", "jap": "は" },
	{ "eng": "to be", "jap": "です" },
	{ "eng": "to be (neg)", "jap": "ではありません/ではないです" },
	{ "eng": "to be (past)", "jap": "でした" },
	{ "eng": "to be (past, neg)", "jap": "ではありませんでした/ではなかったです" },
	{ "eng": "of (particle indicating belonging)", "jap": "の" },
	{ "eng": "attorney, lawyer", "jap": "べんごし" },
	{ "eng": "how do you do", "jap": "はじめまして" },
	{ "eng": "pleased to meet you", "jap": "よろしく おねがいします" },
	{ "eng": "department store", "jap": "デパート" },
	{ "eng": "Japan", "jap": "にほん" },
	{ "eng": "China", "jap": "ちゅうごく" },
	{ "eng": "Germany", "jap": "ドイツ" },
	{ "eng": "UK", "jap": "イギリス" },
	{ "eng": "USA", "jap": "アメリカ" },
	{ "eng": "Australia", "jap": "オーストラリア" },
	{ "eng": "Thailand", "jap": "タイ" },
	{ "eng": "secretary", "jap": "ひしょ" },
	{ "eng": "student", "jap": "がくせい" },
	{ "eng": "engineer", "jap": "エンジニア" },
	{ "eng": "(question particle)", "jap": "か" },
	{ "eng": "yes", "jap": "はい" },
	{ "eng": "no", "jap": "いいえ" },
	{ "eng": "you", "jap": "あなた" },
	{ "eng": "I", "jap": "わたし" },
	{ "eng": "bank", "jap": "ぎんこう" },
	{ "eng": "university, college", "jap": "だいがく" },
	{ "eng": "business card", "jap": "めいし" },
	{ "eng": "company", "jap": "かいしゃ" },
	{ "eng": "please (when giving)", "jap": "どうぞ" },
	{ "eng": "thank you", "jap": "どうも ありがとうございます" },
	{ "eng": "this thing here", "jap": "これ" },
	{ "eng": "name", "jap": "なまえ" },
	{ "eng": "yes (less formal)", "jap": "ええ" },
	{ "eng": "indeed", "jap": "そうです" },
	{ "eng": "zero", "jap": "ゼロ/れい" },
	{ "eng": "one", "jap": "いち" },
	{ "eng": "two", "jap": "に" },
	{ "eng": "three", "jap": "さん" },
	{ "eng": "four", "jap": "よん/し" },
	{ "eng": "five", "jap": "ご" },
	{ "eng": "six", "jap": "ろく" },
	{ "eng": "seven", "jap": "なな/しち" },
	{ "eng": "eight", "jap": "あち" },
	{ "eng": "nine", "jap": "きゅう/く" },
	{ "eng": "address", "jap": "じゅうしょ" },
	{ "eng": "phone", "jap": "でんわ" },
	{ "eng": "number", "jap": "ばんごう" },
	{ "eng": "e-mail address", "jap": "メールアドレス" },
	{ "eng": "cell phone", "jap": "けいたい" },
	{ "eng": "umbrella", "jap": "かさ" },
	{ "eng": "book", "jap": "ほん" },
	{ "eng": "newspaper", "jap": "しんぶん" },
	{ "eng": "key", "jap": "かぎ" },
	{ "eng": "watch, clock", "jap": "とけい" },
	{ "eng": "what", "jap": "なん / なに" },
	{ "eng": "who", "jap": "だれ/どなた" },
	{ "eng": "embassy", "jap": "たいしかん" },
	{ "eng": "what number", "jap": "なんばん" },
	{ "eng": "country", "jap": "くに" },
	{ "eng": "nationality", "jap": "こくせき" },
	{ "eng": "to make a mistake", "jap": "ちがいます (ちがう)" },
	{ "eng": "please (get me ...), I request", "jap": "おねがいします" },
	{ "eng": "receptionist", "jap": "うけつけ" },
	{ "eng": "please go ahead, please enter, please feel free", "jap": "はい、どうぞ" },
	{ "eng": "datebook, small notebook, planner", "jap": "てちょう" },
	{ "eng": "I'm sorry", "jap": "すみません" },
	{ "eng": "one more time, please", "jap": "もう いちど おねがいします" },
	{ "eng": "more", "jap": "もう" },
	{ "eng": "one time", "jap": "いちど" },
	{ "eng": "excuse me", "jap": "すみません" },
	{ "eng": "what time", "jap": "なんじ" },
	{ "eng": "o'clock", "jap": "じ" },
	{ "eng": "woman", "jap": "おんなの ひと" },
	{ "eng": "female", "jap": "おんな" },
	{ "eng": "person", "jap": "ひと" },
	{ "eng": "nine o'clock", "jap": "くじ" },
	{ "eng": "fifty minutes", "jap": "ごじゅっぷん / ごじっぷん" },
	{ "eng": "fifty", "jap": "ごじゅう" },
	{ "eng": "minute", "jap": "-ふん/-ぷん" },
	{ "eng": "from (particle/time and place)", "jap": "から" },
	{ "eng": "until, to (particle/place and time)", "jap": "まで" },
	{ "eng": "p.m., in the afternoon", "jap": "ごご" },
	{ "eng": "you're welcome", "jap": "どういたしまして" },
	{ "eng": "supermarket", "jap": "スーパー" },
	{ "eng": "restaurant", "jap": "レストラン" },
	{ "eng": "post office", "jap": "ゆうびんきょく" },
	{ "eng": "job, work", "jap": "しごと" },
	{ "eng": "meeting", "jap": "かいぎ (に+)" },
	{ "eng": "lunch break", "jap": "ひるやすみ" },
	{ "eng": "noon", "jap": "ひる" },
	{ "eng": "rest, break", "jap": "やすみ" },
	{ "eng": "party", "jap": "パーティー" },
	{ "eng": "movie", "jap": "えいが" },
	{ "eng": "half past (of time)", "jap": "はん" },
	{ "eng": "a.m., in the morning", "jap": "ごぜん" },
	{ "eng": "morning", "jap": "あさ" },
	{ "eng": "breakfast", "jap": "あさごはん" },
	{ "eng": "evening", "jap": "ばん" },
	{ "eng": "meal", "jap": "ごはん" },
	{ "eng": "front desk (of a hotel)", "jap": "フロント" },
	{ "eng": "dinner", "jap": "ばんごはん" },
	{ "eng": "pool", "jap": "プール" },
	{ "eng": "gym", "jap": "ジム" },
	{ "eng": "I see", "jap": "そうですか" },
	{ "eng": "shop, store, restaurant", "jap": "みせ" },
	{ "eng": "may I help you?, welcome to the store", "jap": "いらっしゃいませ" },
	{ "eng": "please show me", "jap": "みせてください" },
	{ "eng": "how much (money)", "jap": "いくら" },
	{ "eng": "yen", "jap": "えん" },
	{ "eng": "also, too, either (particle)", "jap": "も" },
	{ "eng": "well then", "jap": "じゃ" },
	{ "eng": "please give me", "jap": "ください" },
	{ "eng": "hello, good afternoon", "jap": "こんにちは" },
	{ "eng": "television", "jap": "テレビ" },
	{ "eng": "radio", "jap": "ラジオ" },
	{ "eng": "(personal) computer", "jap": "パンコン" },
	{ "eng": "digital camera", "jap": "デジカメ" },
	{ "eng": "video camera", "jap": "ビデオカメラ" },
	{ "eng": "video", "jap": "ビデオ" },
	{ "eng": "camera", "jap": "カメラ" },
	{ "eng": "CD player", "jap": "CDプレーヤー" },
	{ "eng": "CD", "jap": "CD (シーディー?)" },
	{ "eng": "that thing over there", "jap": "あれ" },
	{ "eng": "that thing close to you", "jap": "それ" },
	{ "eng": "magazine", "jap": "ざっし" },
	{ "eng": "DVD", "jap": "DVD (ディーブイディー)" },
	{ "eng": "mechanical pencil", "jap": "シャープペンシル" },
	{ "eng": "ballpoint pen", "jap": "ボールペン" },
	{ "eng": "France", "jap": "フランス" },
	{ "eng": "dictionary", "jap": "じしょ" },
	{ "eng": "English (language)", "jap": "えいご" },
	{ "eng": "(suffix for languages)", "jap": "ご" },
	{ "eng": "(credit) card", "jap": "カード" },
	{ "eng": "is ... al right?", "jap": "ーでも いいですか" },
	{ "eng": "yes, it's fine", "jap": "はい、けっこうです" },
	{ "eng": "thousand", "jap": "せん" },
	{ "eng": "ten thousand", "jap": "いちまん" },
	{ "eng": "one hundred million (10<sup>8</sup>)", "jap": "おく" },
	{ "eng": "one trillion (10<sup>12</sup>)", "jap": "ちょう" },
	{ "eng": "decimal point", "jap": "てん" },
	{ "eng": "part (e.g. in 1/4)", "jap": "ぶん" },
	{ "eng": "ten", "jap": "じゅう" },
	{ "eng": "one hundred", "jap": "ひゃく" },
	{ "eng": "... years old", "jap": "さい" },
	{ "eng": "this ... close to me", "jap": "この" },
	{ "eng": "that ... close to you", "jap": "その" },
	{ "eng": "that ... over there", "jap": "あの" },
	{ "eng": "T-shirt", "jap": "シャツ" },
	{ "eng": "which thing", "jap": "どれ" },
	{ "eng": "blue", "jap": "あおい" },
	{ "eng": "red", "jap": "あかい" },
	{ "eng": "(counter for flat objects)", "jap": "まい" },
	{ "eng": "postcard", "jap": "はがき" },
	{ "eng": "stamp", "jap": "きって" },
	{ "eng": "black", "jap": "くろい" },
	{ "eng": "beer", "jap": "ビール" },
	{ "eng": "apple", "jap": "りんご" },
	{ "eng": "large, big", "jap": "おおきい" },
	{ "eng": "small, little", "jap": "ちいさい" },
	{ "eng": "Switzerland", "jap": "スイス" },
	{ "eng": "(counter for long objects)", "jap": "-ほん" },
	{ "eng": "car", "jap": "くるま" },
	{ "eng": "Italy", "jap": "イタリア" },
	{ "eng": "where, which place", "jap": "どこ" },
	{ "eng": "South Korea", "jap": "かんこく" },
	{ "eng": "tangerine", "jap": "みかん" },
	{ "eng": "kilogram", "jap": "キロ" },
	{ "eng": "wine", "jap": "ウイン" },
	{ "eng": "coffee", "jap": "コーヒー" },
	{ "eng": "cup", "jap": "カップ" },
	{ "eng": "towel", "jap": "タオル" },
	{ "eng": "cream puff", "jap": "シュークリーム" },
	{ "eng": "good morning", "jap": "おはようございます" },
	{ "eng": "hello", "jap": "こんにちは" },
	{ "eng": "good evening", "jap": "こんばんは" },
	{ "eng": "good night", "jap": "おやすみなさい" },
	{ "eng": "good-bye", "jap": "さようなら" },
	{ "eng": "well then ... (when parting from relatives or friends/informal)", "jap": "では/じゃ また" },
	{ "eng": "(when leaving the office or a meeting before other people)", "jap": "おさきに しつれいします" },
	{ "eng": "so long (said to person leaving home)", "jap": "いってらっしゃい" },
	{ "eng": "I'm back", "jap": "ただいま" },
	{ "eng": "welcome home", "jap": "おかえりなさい" },
	{ "eng": "(said before eating a meal)", "jap": "いただきます" },
	{ "eng": "congratulations", "jap": "おめでとうございます" },
	{ "eng": "(said after eating a meal)", "jap": "ごちそうさまでした" },
	{ "eng": "wait a moment, please", "jap": "ちょっと まって ください" },
	{ "eng": "please, go ahead", "jap": "どうぞ おさきに" },
	{ "eng": "take care, be careful", "jap": "きを つけて" },
	{ "eng": "take care of yourself (used toward ill or injured person)", "jap": "おだいじに" },
	{ "eng": "so long (said by person leaving home)", "jap": "いってきます" },
	{ "eng": "-ese, -ian (person from)", "jap": "じん" },
	{ "eng": "now", "jap": "いま" },
	{ "eng": "good-bye (formal, lit., \"I'm going to be rude\")", "jap": "しつれいします" },
	{ "eng": "how many years old?", "jap": "なんさい" },
	{ "eng": "to eat", "jap": "たべます (たべる)" },
	{ "eng": "to wake up/to get up", "jap": "おきます (おきる)" },
	{ "eng": "major (studies)", "jap": "せんこう" },
	{ "eng": "friend", "jap": "ともだち" },
	{ "eng": "pencil", "jap": "えんぴつ" },
	{ "eng": "shoes", "jap": "くつ" },
	{ "eng": "jeans", "jap": "ジインズ" },
	{ "eng": "bike", "jap": "じてんしゃ" },
	{ "eng": "notebook", "jap": "ノート" },
	{ "eng": "wallet", "jap": "さいふ" },
	{ "eng": "hello (on the phone)", "jap": "もしもし" },
	{ "eng": "tomorrow", "jap": "あした" },
	{ "eng": "there (where your listener is)", "jap": "そちら" },
	{ "eng": "to (particle of direction)", "jap": "に" },
	{ "eng": "to go", "jap": "いきます (いく)" },
	{ "eng": "right?; isn't it? (particle)", "jap": "ね" },
	{ "eng": "alone (lit., \"by one person\")", "jap": "ひとりで" },
	{ "eng": "to come", "jap": "きます (irregular verb くる)" },
	{ "eng": "with, together with (particle)", "jap": "と" },
	{ "eng": "well then, in any case (formal form of じゃ)", "jap": "では" },
	{ "eng": "airport", "jap": "くうこう" },
	{ "eng": "station", "jap": "えき" },
	{ "eng": "branch office", "jap": "ししゃ" },
	{ "eng": "park", "jap": "こうえん" },
	{ "eng": "house", "jap": "うち" },
	{ "eng": "to return, to go home", "jap": "かえります (かえる)" },
	{ "eng": "yesterday", "jap": "きのう" },
	{ "eng": "today", "jap": "きょう" },
	{ "eng": "last week", "jap": "せんしゅう" },
	{ "eng": "this week", "jap": "こんしゅう" },
	{ "eng": "next week", "jap": "らいしゅう" },
	{ "eng": "last month", "jap": "せんげつ" },
	{ "eng": "this month", "jap": "こんげつ" },
	{ "eng": "next month", "jap": "らいげつ" },
	{ "eng": "last year", "jap": "きょねん" },
	{ "eng": "this year", "jap": "ことし" },
	{ "eng": "next year", "jap": "らいねん" },
	{ "eng": "London", "jap": "ロンドン" },
	{ "eng": "Tokyo", "jap": "とうきょう" },
	{ "eng": "computer", "jap": "コンピューター" },
	{ "eng": "business", "jap": "ビジネス" },
	{ "eng": "history", "jap": "れきし" },
	{ "eng": "to drink", "jap": "のみます (のむ)" },
	{ "eng": "to read", "jap": "よみます (よむ)" },
	{ "eng": "to write", "jap": "かきます (かく)" },
	{ "eng": "to speak", "jap": "はなします (はなす)" },
	{ "eng": "to do", "jap": "します (irregular verb する)" },
	{ "eng": "(verb suffix: present, pos, formal)", "jap": "-ます" },
	{ "eng": "(verb suffix: present, neg, formal)", "jap": "-ません" },
	{ "eng": "(verb suffix: past, pos, formal)", "jap": "-ました" },
	{ "eng": "(verb suffix: past, neg, formal)", "jap": "-ませんでした" },
	{ "eng": "to see/to watch/to look", "jap": "みます (みる)" },
	{ "eng": "to sleep/go to bed", "jap": "ねます (ねる)" },
	{ "eng": "to study", "jap": "べんきょうを します" },
	{ "eng": "(subject particle)", "jap": "が" },
	{ "eng": "music", "jap": "おんがく" },
	{ "eng": "omelette", "jap": "オムレツ" },
	{ "eng": "omelette with rice", "jap": "オムライス" },
	{ "eng": "a salad", "jap": "サラダ" },
	{ "eng": "fish", "jap": "さかな" },
	{ "eng": "tennis", "jap": "テニス" },
	{ "eng": "hamburger", "jap": "ハンバーガー" },
	{ "eng": "school", "jap": "がっこう" },
	{ "eng": "tea-room", "jap": "きっさてん" },
	{ "eng": "green tea", "jap": "おちゃ" },
	{ "eng": "library", "jap": "としょかん" },
	{ "eng": "sports", "jap": "スポーツ" },
	{ "eng": "(cold) water", "jap": "みず" },
	{ "eng": "the day after tomorrow", "jap": "あさって" },
	{ "eng": "the day before yesterday", "jap": "おととい" },
	{ "eng": "Kyoto", "jap": "きょうと" },
	{ "eng": "when", "jap": "いつ" },
	{ "eng": "oh (interjection used to get someone's attention)", "jap": "あ" },
	{ "eng": "business trip", "jap": "しゅっちょう" },
	{ "eng": "bus", "jap": "バス" },
	{ "eng": "driver", "jap": "うんてんしゅ" },
	{ "eng": "which (used before a noun)", "jap": "どの" },
	{ "eng": "number ... (counter; used as suffix after a number)", "jap": "ばん" },
	{ "eng": "please come in", "jap": "おはいりください" },
	{ "eng": "come right this way", "jap": "どうぞ こちらへ" },
	{ "eng": "by means of (particle indicating means)", "jap": "で" },
	{ "eng": "subway", "jap": "ちかてつ" },
	{ "eng": "at, on, in (particle indicating time)", "jap": "に" },
	{ "eng": "year (counter)", "jap": "ねん" },
	{ "eng": "day (of the week)", "jap": "ようび" },
	{ "eng": "month (counter)", "jap": "がつ" },
	{ "eng": "day (of the month) (counter)", "jap": "にち" },
	{ "eng": "train", "jap": "でんしゃ" },
	{ "eng": "taxi", "jap": "タクシー" },
	{ "eng": "bullet train (in Japan)", "jap": "しんかんせん" },
	{ "eng": "airplane", "jap": "ひこうき" },
	{ "eng": "by foot, by walking", "jap": "あるいて" },
	{ "eng": "by what means", "jap": "なんで" },
	{ "eng": "festival", "jap": "おまつり" },
	{ "eng": "what month", "jap": "なんがつ" },
	{ "eng": "what day (of the month)", "jap": "なんにち" },
	{ "eng": "what day (of the week)", "jap": "なんようび" },
	{ "eng": "birthday", "jap": "たんじょうび" },
	{ "eng": "summer vacation", "jap": "なつやすみ" },
	{ "eng": "summer", "jap": "なつ" },
	{ "eng": "trip, travel", "jap": "りょこう" },
	{ "eng": "hotel", "jap": "ホテル" },
	{ "eng": "(polite prefix)", "jap": "お" },
	{ "eng": "sunday", "jap": "にちようび" },
	{ "eng": "monday", "jap": "げつようび" },
	{ "eng": "tuesday", "jap": "かようび" },
	{ "eng": "wednesday", "jap": "すいようび" },
	{ "eng": "thursday", "jap": "もくようび" },
	{ "eng": "friday", "jap": "きんようび" },
	{ "eng": "saturday", "jap": "どようび" },
	{ "eng": "Okinawa", "jap": "おきなわ (islands on the southwestern tip of Japan)" },
	{ "eng": "family", "jap": "かぞく" },
	{ "eng": "Nikko (scenic area north of Tokyo)", "jap": "にっこう" },
	{ "eng": "be, exist (inanimate objects)", "jap": "あります (ある)" },
	{ "eng": "Buddhist temple", "jap": "おてら" },
	{ "eng": "and, and so on (particle, incomplete enumeration)", "jap": "や" },
	{ "eng": "Shinto shrine", "jap": "じんじゃ" },
	{ "eng": "hot spring (resort)", "jap": "おんせん" },
	{ "eng": "what is a/an ...?", "jap": "ーって なんですか" },
	{ "eng": "spa", "jap": "スパ" },
	{ "eng": "that's nice", "jap": "いいですね" },
	{ "eng": "first floor, ground floor", "jap": "いっかい" },
	{ "eng": "floor, story (counter)", "jap": "かい・がい" },
	{ "eng": "first basement floor", "jap": "ちか いっかい" },
	{ "eng": "basement", "jap": "ちか" },
	{ "eng": "restroom, lavatory", "jap": "おてあらい" },
	{ "eng": "parking lot", "jap": "ちゅうしゃじょう" },
	{ "eng": "refrigerator", "jap": "れいぞうこ" },
	{ "eng": "bed", "jap": "ベッド" },
	{ "eng": "sofa", "jap": "ソファー" },
	{ "eng": "table", "jap": "テーブル" },
	{ "eng": "chair", "jap": "いす" },
	{ "eng": "flower", "jap": "はな" },
	{ "eng": "briefcase, tote bag", "jap": "かばん" },
	{ "eng": "top, above", "jap": "うえ" },
	{ "eng": "bottom, below, under", "jap": "した" },
	{ "eng": "front, before", "jap": "まえ" },
	{ "eng": "back, behind", "jap": "うしろ" },
	{ "eng": "inside, middle", "jap": "なか" },
	{ "eng": "next to", "jap": "となり" },
	{ "eng": "vicinity, nearby", "jap": "ちかく" },
	{ "eng": "to be, to exist, to stay (only of animate objects)", "jap": "います (いる) (-う verb)" },
	{ "eng": "and (particle)", "jap": "と" },
	{ "eng": "nothing", "jap": "なにも ... -ません (neg verb)" },
	{ "eng": "no one", "jap": "だれも ... -ません(neg verb)" },
	{ "eng": "lake", "jap": "みずうみ" },
	{ "eng": "man", "jap": "おとこの ひと" },
	{ "eng": "male, man", "jap": "おとこ" },
	{ "eng": "pen", "jap": "ペン" },
	{ "eng": "sweater", "jap": "セーター" },
	{ "eng": "drawer", "jap": "ひきだし" },
	{ "eng": "pocket", "jap": "ポケット" },
	{ "eng": "traditional Japanese inn", "jap": "りょかん" },
	{ "eng": "waterfall", "jap": "たき" },
	{ "eng": "buckwheat noodle shop", "jap": "そばや" },
	{ "eng": "shop (suffix)", "jap": "や" },
	{ "eng": "(days of the month)", "jap": "tsuitachi<div>futsuka</div><div>mikka</div><div>yokka</div><div>itsuka</div><div>muika</div><div>nanoka</div><div>yōka</div><div>kokonoka</div><div>tōka</div><div>jūichi-nichi</div><div>...</div><div>jūyokka</div><div>...</div><div>jūshichi-nichi</div><div>...</div><div>hatsuka</div><div>...</div><div>nijūyokka</div><div>...</div>" },
	{ "eng": "... year student", "jap": "ねんせい" },
	{ "eng": "to buy", "jap": "かいます (かう)" },
	{ "eng": "to meet", "jap": "あいます (あう) (+に)" },
	{ "eng": "to live in ...", "jap": "... にすんでいます" },
	{ "eng": "usually", "jap": "たいてい" },
	{ "eng": "sometimes", "jap": "ときどき" },
	{ "eng": "quick/early", "jap": "はやい" },
	{ "eng": "weekend", "jap": "しゅうまつ" },
	{ "eng": "left", "jap": "ひだり" },
	{ "eng": "right (direction)", "jap": "みぎ" },
	{ "eng": "over there", "jap": "あそこ" },
	{ "eng": "convenience store", "jap": "コンビニ" },
	{ "eng": "taxi stand", "jap": "タクシーのりば" },
	{ "eng": "bus terminal", "jap": "バスのりば" },
	{ "eng": "police box", "jap": "こうばん" },
	{ "eng": "hospital", "jap": "びょういん" },
	{ "eng": "bookstore", "jap": "ほんや" },
	{ "eng": "bakery", "jap": "パンや" },
	{ "eng": "brood", "jap": "パン" },
	{ "eng": "liquor store", "jap": "さかや" },
	{ "eng": "drugstore", "jap": "くすりや" },
	{ "eng": "medicine", "jap": "くすり" },
	{ "eng": "eraser", "jap": "けしゴム" },
	{ "eng": "stapler", "jap": "ホッチキス" },
	{ "eng": "scissors", "jap": "はさみ" },
	{ "eng": "scotch tape", "jap": "セロテープ" },
	{ "eng": "file", "jap": "ファイル" },
	{ "eng": "how many persons", "jap": "なんにん" },
	{ "eng": "a lot, many", "jap": "たくさん" },
	{ "eng": "boy", "jap": "おとこの こ" },
	{ "eng": "child", "jap": "こ" },
	{ "eng": "girl", "jap": "おんなの こ" },
	{ "eng": "how many (small objects)", "jap": "いくつ" },
	{ "eng": "how many (flat objects)", "jap": "なんまい" },
	{ "eng": "how many (long, thin objects)", "jap": "なんぼん" },
	{ "eng": "here", "jap": "ここ" },
	{ "eng": "garden", "jap": "にわ" },
	{ "eng": "conference room", "jap": "かいぎしつ" },
	{ "eng": "cart (for luggage)", "jap": "カート" },
	{ "eng": "check-in counter", "jap": "チェックインカウンター" },
	{ "eng": "bus stop", "jap": "バスてい" },
	{ "eng": "entrance", "jap": "いりぐち" },
	{ "eng": "about/approximately what time", "jap": "なんじごろ" },
	{ "eng": "about (used of time)", "jap": "ごろ" },
	{ "eng": "Kabuki (traditional theater)", "jap": "かぶき" },
	{ "eng": "(black) tea", "jap": "こうちゃ" },
	{ "eng": "soup", "jap": "スープ" },
	{ "eng": "milk", "jap": "ミルク" },
	{ "eng": "juice", "jap": "ジュース" },
	{ "eng": "sandwich", "jap": "サンドイッチ" },
	{ "eng": "play tenis", "jap": "テニスを します" },
	{ "eng": "to shop", "jap": "かいものを します" },
	{ "eng": "to work", "jap": "しごとを します" },
	{ "eng": "every day", "jap": "まいにち" },
	{ "eng": "every morning", "jap": "まいあさ" },
	{ "eng": "every evening", "jap": "まいばん" },
	{ "eng": "every week", "jap": "まいしゅう" },
	{ "eng": "to jog", "jap": "ジョキングを します" },
	{ "eng": "tempura", "jap": "てんぷら" },
	{ "eng": "steak", "jap": "ステーキ" },
	{ "eng": "bar", "jap": "バー" },
	{ "eng": "gym, sports club", "jap": "スポーツクラブ" },
	{ "eng": "sport(s)", "jap": "スポーツ" },
	{ "eng": "club", "jap": "クラブ" },
	{ "eng": "dog", "jap": "いぬ" },
	{ "eng": "vegetable", "jap": "やさい" },
	{ "eng": "(another person's) wife", "jap": "おくさん" },
	{ "eng": "go for a walk", "jap": "さんぽを します" },
	{ "eng": "play golf", "jap": "ゴルフを します" },
	{ "eng": "tennis court", "jap": "テニスコート" },
	{ "eng": "(humble form of です)", "jap": "でございます" },
	{ "eng": "reservation", "jap": "よやく" },
	{ "eng": "understood; I see; I understand", "jap": "わかりました" },
	{ "eng": "to understand", "jap": "わかります (わかる) (が+)" },
	{ "eng": "(polite form of -さん)", "jap": "さま" },
	{ "eng": "often", "jap": "よく" },
	{ "eng": "be delicious, be tasty", "jap": "おいしいです" },
	{ "eng": "because (particle)", "jap": "から" },
	{ "eng": "whiting", "jap": "きす" },
	{ "eng": "tempura restaurant", "jap": "てんぷらや" },
	{ "eng": "to listen/to ask", "jap": "ききます (きく)" },
	{ "eng": "to phone", "jap": "でんわを します" },
	{ "eng": "to send", "jap": "おくります (おくる)" },
	{ "eng": "(another person's) father", "jap": "おとうさん" },
	{ "eng": "(another person's) mother", "jap": "おかあさん" },
	{ "eng": "(my) father", "jap": "ちち" },
	{ "eng": "(my) mother", "jap": "はは" },
	{ "eng": "(my) wife", "jap": "つま/かない" },
	{ "eng": "(another person's) husband", "jap": "ごしゅじん" },
	{ "eng": "(honorific prefix)", "jap": "ご" },
	{ "eng": "(my) husband", "jap": "おっと/しゅじん" },
	{ "eng": "letter", "jap": "てがみ" },
	{ "eng": "not much (expr.)", "jap": "あまり ... -ません (neg verb)" },
	{ "eng": "president (of a company)", "jap": "しゃちょう" },
	{ "eng": "e-mail", "jap": "メール" },
	{ "eng": "lobby", "jap": "ロビー" },
	{ "eng": "sushi", "jap": "すし" },
	{ "eng": "not at all (expr)", "jap": "ぜんぜん ... -ません (neg verb)" },
	{ "eng": "sushi restaurant", "jap": "すしや" },
	{ "eng": "ice cream", "jap": "アイスクリーム" },
	{ "eng": "this coming", "jap": "こんど" },
	{ "eng": "machine", "jap": "マシーン" },
	{ "eng": "cooking, cuisine", "jap": "りょうり" },
	{ "eng": "bill, check", "jap": "おかんじょう" },
	{ "eng": "receipt", "jap": "りょうしゅうしょ" },
	{ "eng": "please (when giving something)", "jap": "どうぞ" },
	{ "eng": "sweets", "jap": "おかし" },
	{ "eng": "how about...? / would you like some ...?", "jap": "... いかがですか" },
	{ "eng": "said before eating", "jap": "いただきます" },
	{ "eng": "pretty", "jap": "きれい (な)" },
	{ "eng": "very", "jap": "とても" },
	{ "eng": "cupful, glassful (counter)", "jap": "はい・ばい・ぱい" },
	{ "eng": "no thank you, I'm fine / I don't want more", "jap": "いいえ、もう けっこうです" },
	{ "eng": "no thank you", "jap": "けっこうです" },
	{ "eng": "please help yourself to...", "jap": "を どうぞ" },
	{ "eng": "big", "jap": "おおきい" },
	{ "eng": "small", "jap": "ちいさい" },
	{ "eng": "expensive", "jap": "たかい" },
	{ "eng": "inexpensive", "jap": "やすい" },
	{ "eng": "new, fresh", "jap": "あたらしい" },
	{ "eng": "old (not used for people)", "jap": "ふるい" },
	{ "eng": "near", "jap": "ちかい" },
	{ "eng": "far", "jap": "とおい" },
	{ "eng": "difficult", "jap": "むずかしい" },
	{ "eng": "easy", "jap": "やさしい" },
	{ "eng": "sweet", "jap": "あまい" },
	{ "eng": "spicy", "jap": "からい" },
	{ "eng": "hot", "jap": "あつい" },
	{ "eng": "cold", "jap": "さむい" },
	{ "eng": "good", "jap": "いい (よく)" },
	{ "eng": "interesting", "jap": "おもしろい" },
	{ "eng": "busy", "jap": "いそがしい" },
	{ "eng": "lively", "jap": "にぎやか" },
	{ "eng": "quiet", "jap": "しずか" },
	{ "eng": "convenient", "jap": "べんり" },
	{ "eng": "famous", "jap": "ゆうめい" },
	{ "eng": "kind, helpful", "jap": "しんせつ" },
	{ "eng": "free, not busy", "jap": "ひま" },
	{ "eng": "to have a meal", "jap": "しょくじを します" },
	{ "eng": "cake", "jap": "ケーキ" },
	{ "eng": "curry", "jap": "カレー" },
	{ "eng": "game", "jap": "ゲーム" },
	{ "eng": "what kind of", "jap": "どんな" },
	{ "eng": "place", "jap": "ところ" },
	{ "eng": "painting", "jap": "え" },
	{ "eng": "weather", "jap": "てんき" },
	{ "eng": "really", "jap": "ほんとうに" },
	{ "eng": "about five minutes", "jap": "５ふんぐらい" },
	{ "eng": "about, approximately (used for a period, price, amount, etc) [particle]", "jap": "ぐらい" },
	{ "eng": "please wait a minute", "jap": "ちょっと まってください" },
	{ "eng": "a little bit", "jap": "ちょっと" },
	{ "eng": "welcome", "jap": "よく いらっしゃいました" },
	{ "eng": "may I come in? - said when entering someone's home", "jap": "おじゃまします" },
	{ "eng": "to give", "jap": "あげます (あげる)" },
	{ "eng": "to receive", "jap": "もらいます (もらう)" },
	{ "eng": "someone gives something to me (verb)", "jap": "くれます (くれる)" },
	{ "eng": "vase", "jap": "かびん" },
	{ "eng": "color", "jap": "いろ" },
	{ "eng": "favorite", "jap": "すきな (ーな adj.)" },
	{ "eng": "rose", "jap": "ばら" },
	{ "eng": "carnation", "jap": "カーネーション" },
	{ "eng": "tulip", "jap": "チューリップ" },
	{ "eng": "bouquet", "jap": "はなたば" },
	{ "eng": "earring", "jap": "イヤリング" },
	{ "eng": "necklace", "jap": "ネックレス" },
	{ "eng": "ring", "jap": "ゆびわ" },
	{ "eng": "scarf", "jap": "スカーフ" },
	{ "eng": "blouse", "jap": "ブラウス" },
	{ "eng": "ticket", "jap": "きっぷ" },
	{ "eng": "hat, cap", "jap": "ぼうし" },
	{ "eng": "necktie", "jap": "ネクタイ" },
	{ "eng": "coat", "jap": "コート" },
	{ "eng": "gift, souvenir", "jap": "おみやげ" },
	{ "eng": "electronic dictionary", "jap": "でんしじしょ" },
	{ "eng": "Christmas", "jap": "クリスマス" },
	{ "eng": "Valentine's Day", "jap": "バレンタインデー" },
	{ "eng": "chocolate", "jap": "チョコレート" },
	{ "eng": "present", "jap": "プレゼント" },
	{ "eng": "Mother's Day", "jap": "ははの ひ" },
	{ "eng": "Father's Day", "jap": "ちちの ひ" },
	{ "eng": "wedding anniversary", "jap": "けっこんきねんび" },
	{ "eng": "marriage", "jap": "けっこん" },
	{ "eng": "anniversary", "jap": "きねんび" },
	{ "eng": "well", "jap": "よく" },
	{ "eng": "suit, look good on", "jap": "にあいます (にあう)" },
	{ "eng": "it's time to be going, I'd better get going", "jap": "そろそろ しつれいします" },
	{ "eng": "in just a short while", "jap": "そろそろ" },
	{ "eng": "peach", "jap": "もも" },
	{ "eng": "(another person's) house", "jap": "おたく" },
	{ "eng": "fun, enjoyable", "jap": "たのしい" },
	{ "eng": "we", "jap": "わたしたち" },
	{ "eng": "again", "jap": "また" },
	{ "eng": "please come", "jap": "きてください" },
	{ "eng": "boring, tedious", "jap": "つまらない" },
	{ "eng": "bad", "jap": "わるい" },
	{ "eng": "concert", "jap": "コンサート" },
	{ "eng": "clearance sale", "jap": "バーゲンセール" },
	{ "eng": "show", "jap": "ショー" },
	{ "eng": "how was...?", "jap": "どうでしたか" },
	{ "eng": "how", "jap": "どう" },
	{ "eng": "to be (honorific word for います)", "jap": "いらっしゃいます" },
	{ "eng": "please wait a minute (politer way of saying ちょっと まってください)", "jap": "ちょっと おまちください" },
	{ "eng": "cold (aff., present form)", "jap": "さむいです" },
	{ "eng": "cold (neg., present form)", "jap": "さむくないです" },
	{ "eng": "cold (aff., past form)", "jap": "さむかったです" },
	{ "eng": "cold (neg., past form)", "jap": "さむくなかったです" },
	{ "eng": "fireworks display", "jap": "はなびたいかい" },
	{ "eng": "fireworks", "jap": "はなび" },
	{ "eng": "large gathering", "jap": "たいかい" },
	{ "eng": "snow festival", "jap": "ゆきまつり" },
	{ "eng": "snow", "jap": "ゆき" },
	{ "eng": "soccer", "jap": "サッカー" },
	{ "eng": "game, match", "jap": "しあい" },
	{ "eng": "platform", "jap": "ホーム" },
	{ "eng": "west exit", "jap": "にしぐち" },
	{ "eng": "east exit", "jap": "ひがしぐち" },
	{ "eng": "north exit", "jap": "きたぐち" },
	{ "eng": "south exit", "jap": "みなみぐち" },
	{ "eng": "sumo", "jap": "すもう" },
	{ "eng": "'I'm sorry, but it wouldn't be convenient (for me)'", "jap": "ざんねんですが、つごうが わるいです" },
	{ "eng": "talk", "jap": "はなしを します" },
	{ "eng": "that sounds good", "jap": "いいですね" },
	{ "eng": "(concert) hall", "jap": "ホール" },
	{ "eng": "to have a party", "jap": "パーティーを します" },
	{ "eng": "by all means, certainly", "jap": "ぜひ" },
	{ "eng": "true", "jap": "ほんとう" },
	{ "eng": "portable shrine (carried during festivals)", "jap": "おみこし" },
	{ "eng": "to carry (on one's shoulders)", "jap": "かつぎます (かつぐ)" },
	{ "eng": "but", "jap": "でも" },
	{ "eng": "happi coat", "jap": "はっぴ" },
	{ "eng": "mine", "jap": "わたしの" },
	{ "eng": "to lend", "jap": "かします (かす)" },
	{ "eng": "is it all right?", "jap": "いいんですか" },
	{ "eng": "to turn on", "jap": "つけます (つける)" },
	{ "eng": "to turn off", "jap": "けします (けす)" },
	{ "eng": "to carry, hold", "jap": "もちます (もつ)" },
	{ "eng": "to open", "jap": "あけます (あける)" },
	{ "eng": "to close, shut", "jap": "しめます (しめる)" },
	{ "eng": "photograph", "jap": "しゃしん" },
	{ "eng": "take (a photograph)", "jap": "しゃしんを とります (とる)" },
	{ "eng": "time", "jap": "じかん" },
	{ "eng": "class", "jap": "じゅぎょう" },
	{ "eng": "map", "jap": "ちず" },
	{ "eng": "luggage, baggage", "jap": "にもつ" },
	{ "eng": "door", "jap": "ドア" },
	{ "eng": "window", "jap": "まど" },
	{ "eng": "air conditioner", "jap": "エアコン" },
	{ "eng": "money", "jap": "おかね" },
	{ "eng": "this evening", "jap": "こんばん" },
	{ "eng": "next time", "jap": "また こんど" },
	{ "eng": "golf club", "jap": "クラブ" },
	{ "eng": "tool, equipment", "jap": "どうぐ" },
	{ "eng": "to make a photocopy", "jap": "コピーを します" },
	{ "eng": "tennis racket", "jap": "ラケット" },
	{ "eng": "painful, ouch!", "jap": "いたい" },
	{ "eng": "are you all right?", "jap": "だいじょうぶですか" },
	{ "eng": "I'm sorry (for what I did a while ago)", "jap": "すみませんでした" },
	{ "eng": "I feel out of sorts, I don't feel well", "jap": "きぶんが わるいです" },
	{ "eng": "bench", "jap": "ベンチ" },
	{ "eng": "to rest, relax, take time off", "jap": "やすみます (やすむ)" },
	{ "eng": "do you have a moment?", "jap": "ちょっと よろしいですか" },
	{ "eng": "good, all right (polite form of いい; used in interrogative sentences)", "jap": "よろしい" },
	{ "eng": "sales, marketing", "jap": "はんばい" },
	{ "eng": "after (time)", "jap": "の あとで" },
	{ "eng": "factory, manufacturing plant", "jap": "こうじょう" },
	{ "eng": "(electric) light", "jap": "でんき" },
	{ "eng": "report", "jap": "レポート" },
	{ "eng": "art museum", "jap": "びじゅつかん" },
	{ "eng": "buy (ーて form)", "jap": "かって" },
	{ "eng": "meet (ーて form)", "jap": "あって" },
	{ "eng": "return, go home (ーて form)", "jap": "かえって" },
	{ "eng": "go (ーて form)", "jap": "いって" },
	{ "eng": "write (ーて form)", "jap": "かいて" },
	{ "eng": "listen (to), ask (ーて form)", "jap": "きいて" },
	{ "eng": "drink (ーて form)", "jap": "のんで" },
	{ "eng": "read (ーて form)", "jap": "よんで" },
	{ "eng": "turn off (ーて form)", "jap": "けして" },
	{ "eng": "eat (ーて form)", "jap": "たべて" },
	{ "eng": "open (ーて form)", "jap": "あけて" },
	{ "eng": "close (ーて form)", "jap": "しめて" },
	{ "eng": "turn on (ーて form)", "jap": "つけて" },
	{ "eng": "see (ーて form)", "jap": "みて" },
	{ "eng": "come (ーて form)", "jap": "きて" },
	{ "eng": "do (ーて form)", "jap": "して" },
	{ "eng": "to hold a meeting", "jap": "かいぎを します" },
	{ "eng": "why", "jap": "どうして" },
	{ "eng": "particle indicating a purpose", "jap": "に" },
	{ "eng": "conjunction that joins two clauses (particle)", "jap": "が" },
	{ "eng": "product, merchandise", "jap": "しょうひん" },
	{ "eng": "catalog", "jap": "カタログ" },
	{ "eng": "soon, right away", "jap": "すぐ" },
	{ "eng": "please send", "jap": "おくってください" },
	{ "eng": "use", "jap": "つかいます (つかう)" },
	{ "eng": "also, in addition", "jap": "それから" },
	{ "eng": "sample", "jap": "サンプル" },
	{ "eng": "main / central / head office", "jap": "ほんしゃ" },
	{ "eng": "indicates a means of telecommunication or post (particle)", "jap": "で" },
	{ "eng": "turn", "jap": "まがります (まがる)" },
	{ "eng": "stop, park", "jap": "とめます (とめる)" },
	{ "eng": "say", "jap": "いいます (いう)" },
	{ "eng": "teach, show, tell", "jap": "おしえます (おしえる)" },
	{ "eng": "bring something", "jap": "もってきます (もってくる)" },
	{ "eng": "deliver", "jap": "とどけます (とどける)" },
	{ "eng": "wait", "jap": "まちます (まつ) (+を)" },
	{ "eng": "intersection", "jap": "こうさてん" },
	{ "eng": "traffic signal", "jap": "しんごう" },
	{ "eng": "corner", "jap": "かど" },
	{ "eng": "just before", "jap": "てまえ" },
	{ "eng": "ahead", "jap": "さき" },
	{ "eng": "straight ahead", "jap": "まっすぐ" },
	{ "eng": "particle indicating a point of passage", "jap": "を" },
	{ "eng": "fax", "jap": "ファックス" },
	{ "eng": "airmail", "jap": "こうくうびん" },
	{ "eng": "surface mail (boat)", "jap": "ふなびん" },
	{ "eng": "courier service", "jap": "たくはいびん" },
	{ "eng": "say (-て form)", "jap": "いって" },
	{ "eng": "wait (-て form)", "jap": "まって" },
	{ "eng": "turn (-て form)", "jap": "まがって" },
	{ "eng": "take (-て form)", "jap": "とって" },
	{ "eng": "lend (-て form)", "jap": "かして" },
	{ "eng": "show (-て form)", "jap": "みせて" },
	{ "eng": "stop (-て form)", "jap": "とめて" },
	{ "eng": "teach, show, tell (-て form)", "jap": "おしえて" },
	{ "eng": "deliver (-て form)", "jap": "とどけて" },
	{ "eng": "bring (-て form)", "jap": "もってきて" },
	{ "eng": "next", "jap": "つぎ" },
	{ "eng": "pizza", "jap": "ピザ" },
	{ "eng": "menu", "jap": "メニュー" },
	{ "eng": "data, information, material, documents, literature", "jap": "しりょう" },
	{ "eng": "mail, post", "jap": "ゆうびん" },
	{ "eng": "second", "jap": "ふたつめ" },
	{ "eng": "suffix that attaches to a number and makes it an ordinal number", "jap": "め" },
	{ "eng": "(another person's) address", "jap": "ごじゅうしょ" },
	{ "eng": "by (the time)", "jap": "までに" },
	{ "eng": "to, as far as (particle)", "jap": "まで" },
	{ "eng": "white", "jap": "しろい" },
	{ "eng": "thanks (colloquial shortening of どうも ありがとう)", "jap": "どうも" },
	{ "eng": "apartment (in a high-rise building), condominium", "jap": "マンション" },
	{ "eng": "room service", "jap": "ルームサービス" },
	{ "eng": "blanket", "jap": "もうふ" },
	{ "eng": "how may I help you?", "jap": "なんでしょうか" },
	{ "eng": "please take care of", "jap": "あずかってください" },
	{ "eng": "to take care of, to be in charge of", "jap": "あずかります (あずかる)" },
	{ "eng": "bring a person", "jap": "つれてきます (つれてくる)" },
	{ "eng": "take a bath", "jap": "おふろ　に　はいる" },
	{ "eng": "enter", "jap": "はいります (はいる) (-u verb)" },
	{ "eng": "leave", "jap": "でかけます (でかける)" },
	{ "eng": "zebra crossing", "jap": "おおだんほどう" },
	{ "eng": "T crossroads", "jap": "つきあたり" },
	{ "eng": "one (counter for general objects)", "jap": "ひとつ" },
	{ "eng": "two (counter for general objects)", "jap": "ふたつ" },
	{ "eng": "three (counter for general objects)", "jap": "みっつ" },
	{ "eng": "four (counter for general objects)", "jap": "よっつ" },
	{ "eng": "five (counter for general objects)", "jap": "いつつ" },
	{ "eng": "six (counter for general objects)", "jap": "むっつ" },
	{ "eng": "seven (counter for general objects)", "jap": "ななつ" },
	{ "eng": "eight (counter for general objects)", "jap": "やっつ" },
	{ "eng": "nine (counter for general objects)", "jap": "ここのつ" },
	{ "eng": "ten (counter for general objects)", "jap": "とう" },
	{ "eng": "eleven, twelve ... (counter for general objects)", "jap": "じゅういち, じゅうに, ..." },
	{ "eng": "January", "jap": "いちがつ" },
	{ "eng": "February", "jap": "にがつ" },
	{ "eng": "March", "jap": "さんがつ" },
	{ "eng": "April", "jap": "しがつ" },
	{ "eng": "May", "jap": "ごがつ" },
	{ "eng": "June", "jap": "ろくがつ" },
	{ "eng": "July", "jap": "しちがつ" },
	{ "eng": "August", "jap": "はちがつ" },
	{ "eng": "September", "jap": "くがつ" },
	{ "eng": "October", "jap": "じゅうがつ" },
	{ "eng": "December", "jap": "じゅうにがつ" },
	{ "eng": "three persons, ...", "jap": "さんにん, ..." },
	{ "eng": "November", "jap": "じゅういちがつ" },
	{ "eng": "one person", "jap": "ひとり" },
	{ "eng": "two persons", "jap": "ふたり" },
	{ "eng": "get on a train, bus, ...", "jap": "のります (のりる)" },
	{ "eng": "get of a train, bus, ...", "jap": "おります (おりる)" },
	{ "eng": "and (connects actions)", "jap": "そして" },
	{ "eng": "switch between trains, busses, ...", "jap": "のりかえます (のりかえる)" },
	{ "eng": "take (time, ...)", "jap": "かかります (かかる)" },
	{ "eng": "need", "jap": "いります (いる) (が +)" },
	{ "eng": "shall we leave?", "jap": "でましょうか" },
	{ "eng": "to go out, leave", "jap": "でます (でる) (+を)" },
	{ "eng": "how long (time)", "jap": "どのぐらい" },
	{ "eng": "to get on (a vehicle), take", "jap": "のります (のる) (+に)" },
	{ "eng": "get off (a vehicle)", "jap": "おります (おりる) (+を)" },
	{ "eng": "to arrive", "jap": "つきます (つく) (+に)" },
	{ "eng": "minute(s), suffix", "jap": "かん" },
	{ "eng": "hour (suffix, duration)", "jap": "じかん" },
	{ "eng": "5 minutes (period of time)", "jap": "ごふん (かん)" },
	{ "eng": "10 minutes (period of time)", "jap": "じゅっぷん (かん)" },
	{ "eng": "15 minutes (period of time)", "jap": "じゅうごふん (かん)" },
	{ "eng": "20 minutes (period of time)", "jap": "にじゅっぷん (かん)" },
	{ "eng": "25 minutes (period of time)", "jap": "にじゅうごふん (かん)" },
	{ "eng": "30 minutes (period of time)", "jap": "さんじゅっぷん (かん)" },
	{ "eng": "1 hour (period of time)", "jap": "いちじかん" },
	{ "eng": "2 hours (period of time)", "jap": "にじかん" },
	{ "eng": "3 hours (period of time)", "jap": "さんじかん" },
	{ "eng": "4 hours (period of time)", "jap": "よじかん" },
	{ "eng": "5 hours (period of time)", "jap": "ごじかん" },
	{ "eng": "6 hours (period of time)", "jap": "ろくじかん" },
	{ "eng": "1 day (period of time)", "jap": "いちにち" },
	{ "eng": "2 days (period of time)", "jap": "ふつか" },
	{ "eng": "3 days (period of time)", "jap": "みっか" },
	{ "eng": "4 days (period of time)", "jap": "よっか" },
	{ "eng": "5 days (period of time)", "jap": "いつか" },
	{ "eng": "6 days (period of time)", "jap": "むいか" },
	{ "eng": "1 week", "jap": "いっしゅうかん" },
	{ "eng": "2 weeks", "jap": "にしゅうかん" },
	{ "eng": "3 weeks", "jap": "さんしゅうかん" },
	{ "eng": "4 weeks", "jap": "よんしゅうかん" },
	{ "eng": "5 weeks", "jap": "ごしゅうかん" },
	{ "eng": "6 weeks", "jap": "ろくしゅうかん" },
	{ "eng": "1 month", "jap": "いっかげつ" },
	{ "eng": "2 months", "jap": "にかげつ" },
	{ "eng": "3 months", "jap": "さんかげつ" },
	{ "eng": "4 months", "jap": "よんかげつ" },
	{ "eng": "5 months", "jap": "ごかげつ" },
	{ "eng": "6 months", "jap": "ろっかげつ" },
	{ "eng": "1 year", "jap": "いちねん (かん)" },
	{ "eng": "2 years", "jap": "にねん (かん)" },
	{ "eng": "3 years", "jap": "さんねん (かん)" },
	{ "eng": "4 years", "jap": "よねん (かん)" },
	{ "eng": "5 years", "jap": "ごねん (かん)" },
	{ "eng": "6 years", "jap": "ろくねん (かん)" },
	{ "eng": "to walk", "jap": "あるきます (あるく)" },
	{ "eng": "how, in what way", "jap": "どうやって" },
	{ "eng": "New York", "jap": "ニューヨーク" },
	{ "eng": "San Francisco", "jap": "サンフランシスコ" },
	{ "eng": "Paris", "jap": "パリ" },
	{ "eng": "musical", "jap": "ミュージカル" },
	{ "eng": "fair", "jap": "フェア" },
	{ "eng": "Honolulu", "jap": "ホノルル" },
	{ "eng": "travel agency", "jap": "りょこうがいしゃ" },
	{ "eng": "station employee", "jap": "えきいん" },
	{ "eng": "(train) line", "jap": "せん" },
	{ "eng": "platform number one", "jap": "1ばんせん" },
	{ "eng": "platform number", "jap": "ばんせん" },
	{ "eng": "between ... and ...", "jap": "... と ... の あいだに ..." },
	{ "eng": "sea", "jap": "うみ" },
	{ "eng": "to show", "jap": "みせます (みせる)" },
	{ "eng": "departing at", "jap": "はつ" },
	{ "eng": "arriving at (time)", "jap": "ちゃく<br />" },
	{ "eng": "one-way ticket", "jap": "かたみち" },
	{ "eng": "return ticket", "jap": "おうふく" },
	{ "eng": "train going in the direction of (suffix)", "jap": "ほうめん / ゆき" },
	{ "eng": "to be late for ...", "jap": "おくれる (+に)" },
	{ "eng": "to make a reservation", "jap": "よやくします" },
	{ "eng": "woodblock print", "jap": "うきよえ" },
	{ "eng": "may I take (a photograph)?", "jap": "とっても いいですか" },
	{ "eng": "pamphlet, brochure", "jap": "パンフレット" },
	{ "eng": "smoke (a cigarette)", "jap": "たばこを すいます" },
	{ "eng": "cigarette", "jap": "たばこ" },
	{ "eng": "(picture) postcard", "jap": "えはがき" },
	{ "eng": "recorded guide", "jap": "イヤホーンガイド" },
	{ "eng": "earphones, headphones", "jap": "イヤホーン" },
	{ "eng": "guide", "jap": "ガイド" },
	{ "eng": "to use (ーて form)", "jap": "つかって" },
	{ "eng": "to smoke", "jap": "すいます (すう)" },
	{ "eng": "to smoke (ーて form)", "jap": "すって" },
	{ "eng": "to enter (ーて form)", "jap": "はいって" },
	{ "eng": "to rest", "jap": "やすみます (やすむ)" },
	{ "eng": "to rest (ーて form)", "jap": "やすんで" },
	{ "eng": "customer, client (polite form)", "jap": "おきゃくさん" },
	{ "eng": "(business) card", "jap": "カード" },
	{ "eng": "romanized Japanese", "jap": "ローマじ" },
	{ "eng": "to put", "jap": "おきます (おく)" },
	{ "eng": "to put (ーて form)", "jap": "おいて" },
	{ "eng": "Mt. Fuji", "jap": "ふじさん" },
	{ "eng": "(said when you are about to take someone's photo)", "jap": "とりますよ" },
	{ "eng": "flash", "jap": "フラッシュ" },
	{ "eng": "please don't use", "jap": "つかわないでください" },
	{ "eng": "to smoke (ーない form)", "jap": "すわない" },
	{ "eng": "to use (ーない form)", "jap": "つかわない" },
	{ "eng": "to stand up", "jap": "たちます (たつ)" },
	{ "eng": "to stand up (ーない form)", "jap": "たたない" },
	{ "eng": "to drink (ーない form)", "jap": "のまない" },
	{ "eng": "to take (a photograph) (ーない form)", "jap": "とらない" },
	{ "eng": "to open (ーない form)", "jap": "あけない" },
	{ "eng": "to close (ーない form)", "jap": "しめない" },
	{ "eng": "to stop, park (ーない form)", "jap": "とめない" },
	{ "eng": "to meet (ーない form)", "jap": "あわない" },
	{ "eng": "to put in, add", "jap": "いれます (いれる)" },
	{ "eng": "to put in, add (ーない form)", "jap": "いれない" },
	{ "eng": "no smoking, non-smoking", "jap": "きんえん" },
	{ "eng": "no parking", "jap": "ちゅうしゃきんし" },
	{ "eng": "Japanese (green) horseradish", "jap": "わさび" },
	{ "eng": "exit", "jap": "でぐち" },
	{ "eng": "baby", "jap": "あかちゃん" },
	{ "eng": "ketchup", "jap": "ケチャップ" },
	{ "eng": "mayonnaise", "jap": "マヨネーズ" },
	{ "eng": "iced coffee", "jap": "アイスコーヒー" },
	{ "eng": "sugar", "jap": "さとう" },
	{ "eng": "'don't worry about it', 'don't let it bother you'", "jap": "きに しないでください" },
	{ "eng": "to worry (about), be bothered (by)", "jap": "きに します" },
	{ "eng": "(medical) doctor", "jap": "いしゃ" },
	{ "eng": "is/are explaining", "jap": "せつめいをしています" },
	{ "eng": "to explain", "jap": "せつめいをします" },
	{ "eng": "sales department (office)", "jap": "えいぎょうぶ" },
	{ "eng": "but (particle joining two clauses)", "jap": "が" },
	{ "eng": "to clean", "jap": "そうじをします" },
	{ "eng": "to make", "jap": "つくります (つくる)" },
	{ "eng": "elevator", "jap": "エレベーター" },
	{ "eng": "escalator", "jap": "エスカレータ" },
	{ "eng": "stairs", "jap": "かいだん" },
	{ "eng": "already", "jap": "もう" },
	{ "eng": "see you later; talk to you later", "jap": "またあとで" },
	{ "eng": "not yet", "jap": "まだ" },
	{ "eng": "a little more", "jap": "もうすこし" },
	{ "eng": "to sell", "jap": "うっています" },
	{ "eng": "to sell (-masu)", "jap": "うります (うる)" },
	{ "eng": "to live (-masu)", "jap": "すみます (すむ)" },
	{ "eng": "I'm sorry to have to tell you this (politer way of saying すみません)", "jap": "もうしわけございません" },
	{ "eng": "very much, extremely (politer way of saying とても)", "jap": "たいへん" },
	{ "eng": "to know", "jap": "しっています" },
	{ "eng": "to be employed", "jap": "つとめています (+に)" },
	{ "eng": "to be employed (-masu)", "jap": "つとめます (つとめる) (+に)" },
	{ "eng": "child (related)", "jap": "こども" },
	{ "eng": "child (unrelated)", "jap": "おこさん" },
	{ "eng": "son (related)", "jap": "むすこ" },
	{ "eng": "son (unrelated)", "jap": "むすこさん" },
	{ "eng": "daughter (related)", "jap": "むすめ" },
	{ "eng": "daughter (unrelated)", "jap": "おじょうさん / むすめさん" },
	{ "eng": "older brother (related)", "jap": "あに" },
	{ "eng": "older brother (unrelated)", "jap": "おにいさん" },
	{ "eng": "older sister (related)", "jap": "あね" },
	{ "eng": "older sister (unrelated)", "jap": "おねえさん" },
	{ "eng": "younger brother (related)", "jap": "おとうと" },
	{ "eng": "younger brother (unrelated)", "jap": "おとうとさん" },
	{ "eng": "younger sister (related)", "jap": "いもうと" },
	{ "eng": "younger sister (unrelated)", "jap": "いもうとさん" },
	{ "eng": "and (connecting sentences)", "jap": "そして" },
	{ "eng": "electronics store", "jap": "でんきや" },
	{ "eng": "maple syrup", "jap": "メープルシロップ" },
	{ "eng": "actually, I don't know", "jap": "さあわかりません" },
	{ "eng": "to know (-masu)", "jap": "しります (しる)" },
	{ "eng": "self introduction", "jap": "じこしょうかい" },
	{ "eng": "pause", "jap": "きゅうけい" },
	{ "eng": "to be lean", "jap": "やせています" },
	{ "eng": "to be fat", "jap": "ふとっています" },
	{ "eng": "to sit down", "jap": "すわります (すわる)" },
	{ "eng": "to be seated", "jap": "すわっています" },
	{ "eng": "to wear (from the neck down, above the waist)", "jap": "きています" },
	{ "eng": "to wear (glasses)", "jap": "かけています" },
	{ "eng": "to wear (from the waist down)", "jap": "はいています" },
	{ "eng": "to wear (on the head)", "jap": "かぶっています" },
	{ "eng": "parents", "jap": "（ご）りょうしん" },
	{ "eng": "grandmother", "jap": "そぼ　（おばあさん）" },
	{ "eng": "grandfather", "jap": "そふ　（おじいさん）" },
	{ "eng": "siblings", "jap": "（ご）きょうだい" },
	{ "eng": "sisters", "jap": "（ご）しまい" },
	{ "eng": "grandchildren", "jap": "まご　（おまごさん）" },
	{ "eng": "uncle", "jap": "おじ（さん）" },
	{ "eng": "aunt", "jap": "おば（さん）" },
	{ "eng": "nephew", "jap": "おい（ごさん）" },
	{ "eng": "niece", "jap": "めい（ごさん）" },
	{ "eng": "cousin", "jap": "いとこ（さん）" },
	{ "eng": "short (person)", "jap": "<div>せがひくい</div>" },
	{ "eng": "tall (person)", "jap": "せがたかい" },
	{ "eng": "at that moment", "jap": "のとき" },
	{ "eng": "short, low", "jap": "ひく" },
	{ "eng": "eye", "jap": "め" },
	{ "eng": "to get fat", "jap": "ふとる" },
	{ "eng": "to put on (clothes, above the waist)", "jap": "きます (きる)" },
	{ "eng": "happy new year (31 december)", "jap": "よいおとしを" },
	{ "eng": "happy new year (1 january)", "jap": "あけまして　おめでとう" },
	{ "eng": "to contain (e.g. a dish)", "jap": "はいています (+に,+が)" },
	{ "eng": "to comprise (e.g. a set meal)", "jap": "ついています (+に,+が)" },
	{ "eng": "cheese", "jap": "チーズ" },
	{ "eng": "tomato", "jap": "トマト" },
	{ "eng": "lettuce", "jap": "レタス" },
	{ "eng": "pickles", "jap": "ピクルス" },
	{ "eng": "fried noodles", "jap": "やきそば" },
	{ "eng": "pork meat", "jap": "ぶたにく" },
	{ "eng": "shrimp", "jap": "えび" },
	{ "eng": "tofu", "jap": "とうふ" },
	{ "eng": "ginger", "jap": "しょうが" },
	{ "eng": "chili pepper", "jap": "とうがらし" },
	{ "eng": "set menu", "jap": "セット" },
	{ "eng": "boiled rice, meal", "jap": "ごはん" },
	{ "eng": "miso soup", "jap": "みそしる" },
	{ "eng": "breakfast menu", "jap": "モーニングセット" },
	{ "eng": "toast", "jap": "トースト" },
	{ "eng": "egg", "jap": "たまご" },
	{ "eng": "evening, night", "jap": "よる" },
	{ "eng": "hobby", "jap": "しゅみ" },
	{ "eng": "to borrow", "jap": "かります (かりる)" },
	{ "eng": "to swim", "jap": "およぎます (およぐ)" },
	{ "eng": "to yell", "jap": "よびます (よぶ)" },
	{ "eng": "be skilled, be good at (-na adj.)", "jap": "じょうずです" },
	{ "eng": "like (-na adj.)", "jap": "すきです" },
	{ "eng": "understand", "jap": "わかります" },
	{ "eng": "skiing", "jap": "スキー" },
	{ "eng": "baseball", "jap": "やきゅう" },
	{ "eng": "swimming", "jap": "スイエイ" },
	{ "eng": "fruit", "jap": "くだもの" },
	{ "eng": "kanji", "jap": "かんじ" },
	{ "eng": "whiskey", "jap": "ウイスキー" },
	{ "eng": "dancing", "jap": "ダンス" },
	{ "eng": "Chinese language", "jap": "ちゅうごくご" },
	{ "eng": "Korean language", "jap": "かんこくご" },
	{ "eng": "German language", "jap": "ドイツご" },
	{ "eng": "Italian food", "jap": "イタリアりょうり" },
	{ "eng": "jazz", "jap": "ジャズ" },
	{ "eng": "piano", "jap": "ピアノ" },
	{ "eng": "ocean, sea", "jap": "うみ" },
	{ "eng": "French food", "jap": "フランスりょうり" },
	{ "eng": "that person over there", "jap": "あちら" },
	{ "eng": "learn, take lessons in", "jap": "ならいます" },
	{ "eng": "introduce", "jap": "しょうかいします" },
	{ "eng": "kendo", "jap": "けんどう" },
	{ "eng": "practice", "jap": "れんしゅうをします" },
	{ "eng": "fine, wonderful, lovely (-na adj.)", "jap": "すてきな" },
	{ "eng": "cooking school", "jap": "クッキングスクール" },
	{ "eng": "Japanese food", "jap": "にほんりょうり" },
	{ "eng": "want to learn", "jap": "ならいたいです" },
	{ "eng": "judo", "jap": "じゅうどう" },
	{ "eng": "flower arranging", "jap": "いけばな" },
	{ "eng": "tea ceremony", "jap": "おちゃ" },
	{ "eng": "head", "jap": "あたま" },
	{ "eng": "tooth", "jap": "は" },
	{ "eng": "throat", "jap": "のど" },
	{ "eng": "belly, stomach", "jap": "おなか" },
	{ "eng": "shoulder", "jap": "かた" },
	{ "eng": "back", "jap": "せなか" },
	{ "eng": "lower back", "jap": "こし" },
	{ "eng": "hand, arm", "jap": "て" },
	{ "eng": "leg, foot", "jap": "あし" },
	{ "eng": "want to go", "jap": "いきたいです" },
	{ "eng": "be painful, hurt", "jap": "いたいです" },
	{ "eng": "furniture", "jap": "かぐ" },
	{ "eng": "the future", "jap": "しょうらい" },
	{ "eng": "warm", "jap": "あたたかい" },
	{ "eng": "town", "jap": "まち" },
	{ "eng": "what's the matter with you?", "jap": "どうしましたか" },
	{ "eng": "fever", "jap": "ねつ" },
	{ "eng": "degree (heat)", "jap": "ーど" },
	{ "eng": "farewell party", "jap": "そうべつかい" },
	{ "eng": "be late", "jap": "おそいです" }];